Twitter pics
noahkw/botw-bot pull request #56
Opened 2021-05-29 20:47 UTC by chaseemory

Lets Tweet!

2021-05-30 01:45 UTC, noahkw requested changes
Thanks for the PR <3

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            servers_dict[server._guild].add(server._channel)
Directly construct a set of channels here (`.channel`)

2021-05-30 01:45 UTC, noahkw commented on db.py
> +    return [r for (r,) in result]
```suggestion
async def get_twitter_settings(session, guild_id):
    statement = select(TwtSetting).where(TwtSetting._guild == guild_id)
    result = (await session.execute(statement)).first()

    return result[0] if result else None
```

This also makes the multiple [0]'s above obsolete

2021-05-30 01:45 UTC, noahkw commented on db.py
> +    return [r for (r,) in result]
```suggestion
async def get_twitter_filters(session, filter_=None, guild_id=None):
    if guild_id and filter_:
        statement = select(TwtFilter).where(
            (TwtFilter._filter == filter_) & (TwtFilter._guild == guild_id)
        )
    elif guild_id:
        statement = select(TwtFilter).where(TwtFilter._guild == guild_id)
    result = (await session.execute(statement)).all()

    return [r for (r,) in result]
```

2021-05-30 01:45 UTC, noahkw commented on db.py
> +    return [r for (r,) in result]
```suggestion
async def get_twitter_accounts(session, account_id=None, guild_id=None):
    if guild_id and account_id:
        statement = select(TwtAccount).where(
            (TwtAccount.account_id == account_id) & (TwtAccount._guild == guild_id)
        )
    elif account_id:
        statement = select(TwtAccount).where(TwtAccount.account_id == account_id)
    elif guild_id:
        statement = select(TwtAccount).where(TwtAccount._guild == guild_id)
    else:
        statement = select(TwtAccount)
    result = (await session.execute(statement)).all()

    return [r for (r,) in result]
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +                video_bytes = BytesIO(await response.read())
Pass session instead of creating one here

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +                    )
```suggestion
                    logger.debug(
                        f"stream processing @{tweet.user.screen_name} - {tweet.id_str}"
                    )
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +        await ctx.send_help(self.twitter)
```suggestion
    )
    async def twitter(self, ctx):
        if not ctx.invoked_subcommand:
            await ctx.send_help(self.twitter)
```

Change all the other groups too.

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            id=1230927030163628032, include_entities=False, trim_user=True
Magic number? Better as a constant. Though I am not sure what this does.

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +                logger.info(f"{ctx.guild.name} enabled twitter")
```suggestion
                logger.info(f"{ctx.guild.name} ({ctx.guild.id}) enabled twitter")
```
Best to change other occurrences too. Just the name isn't very useful

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +        tweet_ids = [_tweet_url.group(4) for _tweet_url in tweet_urls]
```suggestion
        tweet_ids = [tweet_url_.group(4) for tweet_url_ in tweet_urls]
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +        await ctx.send_help(self.set)
See the comment above

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            server_settings[0].default_channel = channel.id if channel else 0
```suggestion
            server_settings[0].default_channel = channel.id if channel else None
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +                logger.info(f"{ctx.guild.name} updated {tag_conditioned} to #{channel}")
```suggestion
                logger.debug(f"{ctx.guild.name} updated {tag_conditioned} to #{channel}")
```
Most of these would be pretty spammy. Not sure whether I'd want to see them in my info logs

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +                await session.commit()
```suggestion
    async def add_filter(self, ctx, filter_: commands.clean_content):
        """
        Add a filter to your tweet stream, any tweets containing these filters will not be posted.

        Example usage:
        `{prefix}twitter add filter 프리뷰`
        """
        async with self.bot.Session() as session:
            # check if filter already exists
            twitter_filter = await db.get_twitter_filters(
                session, filter_=filter_, guild_id=ctx.guild.id
            )
            if twitter_filter:
                await ctx.send(f'Filter `{filter_}` already exists')
            else:
                twitter_filter = TwtFilter(_guild=ctx.guild.id, filter_=filter_)
                logger.info(f"{ctx.guild.name} ({ctx.guild.id}) added filter - {filter_}")
                session.add(twitter_filter)
                await session.commit()
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            return None
Better to show an error to the user.

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            return None
Send an error msg here too

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            await session.commit()
```suggestion
    async def remove_filter(self, ctx, filter_: commands.clean_content):
        """
        Remove a filter to your tweet stream, any tweets containing these filters will not be posted.

        Example usage:
        `{prefix}twitter remove filter 프리뷰`
        """
        async with self.bot.Session() as session:
            await db.delete_twitter_filters(
                session, filter_=filter_, guild_id=ctx.guild.id
            )
            logger.info(f"{ctx.guild.name} removed filter - {filter_}")
            await session.commit()
```

2021-05-30 01:45 UTC, noahkw commented on db.py
> +    return [r for (r,) in result]
```suggestion
async def get_twitter_accounts(session, account_id=None, guild_id=None):
    if guild_id and account_id:
        statement = select(TwtAccount).where(
            (TwtAccount.account_id == account_id) & (TwtAccount._guild == guild_id)
        )
    elif account_id:
        statement = select(TwtAccount).where(TwtAccount.account_id == account_id)
    elif guild_id:
        statement = select(TwtAccount).where(TwtAccount._guild == guild_id)
    else:
        statement = select(TwtAccount)
    result = (await session.execute(statement)).all()

    return [r for (r,) in result]
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +                            if "extended_entities" in tweet:
```suggestion
                        if tweet and "extended_entities" in tweet:
```

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +        KR_UTC_OFFSET = timedelta(hours=9)
Put this in line 50

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            server_settings = await db.get_twitter_settings(session, server)
Doing queries in a for loop is a bad idea. Should pass the list of servers to get_twitter_filters/get_twitter_settings.

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +        async with self.bot.Session() as session:
Pass a session instead of creating one here

2021-05-30 01:45 UTC, noahkw commented on cogs/Twitter.py
> +            await self.manage_twt(tweet, guild_id=ctx.guild.id)
lol

2021-05-30 03:55 UTC, chaseemory commented on db.py
> +    return [r for (r,) in result]
it do

2021-05-31 20:23 UTC, noahkw approved these changes
looks good to me

2021-05-31 20:48 UTC, closed without merging